version: '3.8'

services:
  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - "27018:27017" # Expose for local access if running app outside docker too
    environment:
      MONGO_INITDB_DATABASE: catalog
    volumes:
      - mongo-data:/data/db
    networks:
      - middleware-net

  redis:
    image: redis:7-alpine
    container_name: redis_local
    ports:
      - "6379:6379"
    networks:
      middleware-net:
        aliases:
          - redis

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"     # AMQP port
      - "15672:15672"   # Management UI
    volumes:
      - ./src/test/resources/definitions.json:/etc/rabbitmq/definitions.json
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit load_definitions \"/etc/rabbitmq/definitions.json\""
    restart: always
    networks:
      - middleware-net


  graphql-gateway:
    image: spring-base_graphql-gateway:latest
    container_name: graphql_gateway_local
    hostname: graphql-gateway
    ports:
      - "8060:8080"
      - "5009:5005"
    environment:
      - JAVA_TOOL_OPTIONS=--enable-preview -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - SPRING_PROFILES_ACTIVE=LOCAL
      - REGISTRY_ENDPOINT=http://registry:8080/registry
      - GRAPHQL_ENABLED=false
      - REGISTRY_CONSISTENCY_SCHEDULER_ENABLED=false
      - LOG_API_KEY=${LOG_API_KEY}
      - JMS_PASSWORD=${JMS_PASSWORD}
    networks:
      middleware-net:
        aliases:
          - graphql-gateway
    depends_on:
      - registry
      - catalog-service
      - product-service-debug
      - rabbitmq


  registry:
    # Build context as passed by user, assuming files exist relative to execution context or built image exists
    # build:
    #   context: .
    #   dockerfile: parent/registry/boot/Dockerfile.runtime
    image: spring-base_registry:latest
    container_name: registry_local
    hostname: registry
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - JAVA_TOOL_OPTIONS=--enable-preview -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - SPRING_PROFILES_ACTIVE=LOCAL
      - REGISTRY_ENDPOINT=http://registry:8080/registry
      - REDIS_ADDRESS=redis://redis:6379
      - GRAPHQL_ENABLED=false
      - REGISTRY_CONSISTENCY_SCHEDULER_ENABLED=false
      - REGISTRY_TOPOLOGY_RECONCILER_ENABLED=true
      - REGISTRY_TOPOLOGY_RECONCILER_CRON=*/5 * * * * *
      - REGISTRY_TOPOLOGY_RECONCILER_MAX_NO_AVAIL=3
      - REGISTRY_TOPOLOGY_RECONCILER_REGISTER_RESOURCE_PATH=/resources/register
      - LOG_API_KEY=${LOG_API_KEY}
      - JMS_PASSWORD=${JMS_PASSWORD}
    networks:
      middleware-net:
        aliases:
          - registry
    depends_on:
      - redis
      - rabbitmq

  catalog-service:
    build:
      context: ./catalog-service
      dockerfile: Dockerfile
    image: catalog-service:latest
    container_name: catalog_local
    hostname: catalog
    ports:
      - "8070:8080"
      - "5008:5005"
    environment:
      - JAVA_TOOL_OPTIONS=--enable-preview -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Djava.net.preferIPv4Stack=true -Dio.netty.resolver.dns.ndots=1 -Dio.netty.resolver.dns.noSearchDomains=true -Dio.netty.resolver.dns.queryTimeoutMillis=10000
      - SERVER_PORT=8080
      - SECURITY_TYPE=OAUTH2
      - REGISTRY_ENDPOINT=http://registry:8080/registry
      - SERVER_CONTEXT_PATH=/catalog
      - MONGO_URI=mongodb://mongo:27017/catalog
      - REDIS_ADDRESS=redis://redis:6379
      - SPRING_PROFILES_ACTIVE=local
      - GRAPHQL_ENABLED=true
      - GRAPHQL_CATALOG_CLUSTER_NAME=catalog
      - GRAPHQL_CATALOG_NAMESPACE=catalog
      - REGISTRY_CONSISTENCY_SCHEDULER_ENABLED=true
      - REGISTRY_CONSISTENCY_SCHEDULER_CRON=*/10 * * * * *
      - LOG_API_KEY=${LOG_API_KEY}
      - LOG_REQUEST_ENABLED=true
      - LOG_RESPONSE_ENABLED=true
      - LOG_RESPONSE_TIME_ENABLED=false
      - BASIC_AUTH_CATALOG_ADMIN=admin
      - BASIC_AUTH_CATALOG_ADMIN_PASSWORD=${BASIC_AUTH_CATALOG_ADMIN_PASSWORD}
      - OAUTH2_ISSUER_URI=http://localhost:8081/realms/spring-middleware
      - OAUTH2_JWK_SET_URI=http://keycloak:8080/realms/spring-middleware/protocol/openid-connect/certs
      - OAUTH2_AUTHORITIES_CLAIM_PATH=$$.resource_access.catalog-service.roles[*]
      - API_KEY_PRODUCT_SERVICE=${API_KEY_PRODUCT_ADMIN}
      - API_KEY_CATALOG_SERVICE=${API_KEY_CATALOG_SERVICE}
      - OAUTH2_CLIENT_SECRET_PRODUCT_SERVICE=${OAUTH2_CLIENT_SECRET_PRODUCT_SERVICE}
      - JMS_PASSWORD=${JMS_PASSWORD}
    depends_on:
      - product-service-debug
      - mongo
      - registry
    networks:
      - middleware-net

  product-service-debug:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    image: product-service:latest
    container_name: product_service_debug
    hostname: product
    ports:
      - "8090:8080"
      - "5007:5007"
    environment:
      - JAVA_TOOL_OPTIONS=--enable-preview -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5007 -Djava.net.preferIPv4Stack=true -Dio.netty.resolver.dns.ndots=1 -Dio.netty.resolver.dns.noSearchDomains=true -Dio.netty.resolver.dns.queryTimeoutMillis=10000
      - SERVER_PORT=8080
      - SECURITY_TYPE=OAUTH2
      - SERVER_CONTEXT_PATH=/product
      - REGISTRY_ENDPOINT=http://registry:8080/registry
      - MONGO_URI=mongodb://mongo:27017/product
      - GRAPHQL_ENABLED=true
      - GRAPHQL_PRODUCT_CLUSTER_NAME=product
      - GRAPHQL_PRODUCT_NAMESPACE=product
      - SPRING_PROFILES_ACTIVE=local
      - REGISTRY_CONSISTENCY_SCHEDULER_ENABLED=true
      - REGISTRY_CONSISTENCY_SCHEDULER_CRON=*/10 * * * * *
      - LOG_API_KEY=${LOG_API_KEY}
      - LOG_REQUEST_ENABLED=true
      - LOG_RESPONSE_ENABLED=true
      - LOG_RESPONSE_TIME_ENABLED=false
      - JMS_PASSWORD=${JMS_PASSWORD}
      - OAUTH2_ISSUER_URI=http://keycloak:8080/realms/spring-middleware
      - OAUTH2_JWK_SET_URI=http://keycloak:8080/realms/spring-middleware/protocol/openid-connect/certs
      - OAUTH2_AUTHORITIES_CLAIM_PATH=$$.resource_access.product-service.roles[*]
      - API_KEY_PRODUCT_ADMIN=${API_KEY_PRODUCT_ADMIN}
      - API_KEY_PRODUCT_WRITER=${API_KEY_PRODUCT_WRITER}
      - API_KEY_PRODUCT_READER=${API_KEY_PRODUCT_READER}
      - OAUTH2_TOKEN_URI_PRODUCT_SERVICE=http://keycloak:8080/realms/spring-middleware/protocol/openid-connect/token
      - BASIC_AUTH_PRODUCT_ADMIN_PASSWORD=${BASIC_AUTH_PRODUCT_ADMIN_PASSWORD}
    depends_on:
      - mongo
      - registry
    networks:
      middleware-net:
        aliases:
          - product


  nginx:
    image: nginx:latest
    hostname: product
    ports:
      - "8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - product-service-1
      - product-service-2
      - product-service-3
    networks:
      middleware-net:
        aliases:
          - product

  product-service-1:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    image: product-service:latest
    hostname: product-1
    expose:
      - "8080"
      - "5005"
    environment:
      - JAVA_TOOL_OPTIONS=--enable-preview -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5007 -Djava.net.preferIPv4Stack=true -Dio.netty.resolver.dns.ndots=1 -Dio.netty.resolver.dns.noSearchDomains=true -Dio.netty.resolver.dns.queryTimeoutMillis=10000
      - SERVER_PORT=8080
      - SERVER_CONTEXT_PATH=/product
      - SECURITY_TYPE=BASIC_AUTH
      - REGISTRY_ENDPOINT=http://registry:8080/registry
      - MONGO_URI=mongodb://mongo:27017/product
      - GRAPHQL_ENABLED=true
      - GRAPHQL_PRODUCT_CLUSTER_NAME=product
      - GRAPHQL_PRODUCT_NAMESPACE=product
      - SPRING_PROFILES_ACTIVE=local
      - REGISTRY_CONSISTENCY_SCHEDULER_ENABLED=true
      - REGISTRY_CONSISTENCY_SCHEDULER_CRON=*/10 * * * * *
      - LOG_API_KEY=${LOG_API_KEY}
      - LOG_REQUEST_ENABLED=true
      - LOG_RESPONSE_ENABLED=true
      - LOG_RESPONSE_TIME_ENABLED=false
      - JMS_PASSWORD=${JMS_PASSWORD}
      - OAUTH2_ISSUER_URI=http://keycloak:8080/realms/spring-middleware
      - OAUTH2_JWK_SET_URI=http://keycloak:8080/realms/spring-middleware/protocol/openid-connect/certs
      - OAUTH2_AUTHORITIES_CLAIM_PATH=$$.resource_access.product-service.roles[*]
      - API_KEY_PRODUCT_ADMIN=${API_KEY_PRODUCT_ADMIN}
      - API_KEY_PRODUCT_WRITER=${API_KEY_PRODUCT_WRITER}
      - API_KEY_PRODUCT_READER=${API_KEY_PRODUCT_READER}
      - OAUTH2_TOKEN_URI_PRODUCT_SERVICE=http://keycloak:8080/realms/spring-middleware/protocol/openid-connect/token
      - BASIC_AUTH_PRODUCT_ADMIN_PASSWORD=${BASIC_AUTH_PRODUCT_ADMIN_PASSWORD}
    depends_on:
      - mongo
      - registry
    networks:
      - middleware-net

  product-service-2:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    image: product-service:latest
    hostname: product-2
    expose:
      - "8080"
      - "5005"
    environment:
      - JAVA_TOOL_OPTIONS=--enable-preview -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5007 -Djava.net.preferIPv4Stack=true -Dio.netty.resolver.dns.ndots=1 -Dio.netty.resolver.dns.noSearchDomains=true -Dio.netty.resolver.dns.queryTimeoutMillis=10000
      - SERVER_PORT=8080
      - SERVER_CONTEXT_PATH=/product
      - SECURITY_TYPE=BASIC_AUTH
      - REGISTRY_ENDPOINT=http://registry:8080/registry
      - MONGO_URI=mongodb://mongo:27017/product
      - GRAPHQL_ENABLED=true
      - GRAPHQL_PRODUCT_CLUSTER_NAME=product
      - GRAPHQL_PRODUCT_NAMESPACE=product
      - SPRING_PROFILES_ACTIVE=local
      - REGISTRY_CONSISTENCY_SCHEDULER_ENABLED=true
      - REGISTRY_CONSISTENCY_SCHEDULER_CRON=*/10 * * * * *
      - LOG_API_KEY=${LOG_API_KEY}
      - LOG_REQUEST_ENABLED=true
      - LOG_RESPONSE_ENABLED=true
      - LOG_RESPONSE_TIME_ENABLED=false
      - JMS_PASSWORD=${JMS_PASSWORD}
      - OAUTH2_ISSUER_URI=http://keycloak:8080/realms/spring-middleware
      - OAUTH2_JWK_SET_URI=http://keycloak:8080/realms/spring-middleware/protocol/openid-connect/certs
      - OAUTH2_AUTHORITIES_CLAIM_PATH=$$.resource_access.product-service.roles[*]
      - API_KEY_PRODUCT_ADMIN=${API_KEY_PRODUCT_ADMIN}
      - API_KEY_PRODUCT_WRITER=${API_KEY_PRODUCT_WRITER}
      - API_KEY_PRODUCT_READER=${API_KEY_PRODUCT_READER}
      - OAUTH2_TOKEN_URI_PRODUCT_SERVICE=http://keycloak:8080/realms/spring-middleware/protocol/openid-connect/token
      - BASIC_AUTH_PRODUCT_ADMIN_PASSWORD=${BASIC_AUTH_PRODUCT_ADMIN_PASSWORD}
    depends_on:
      - mongo
      - registry
    networks:
      - middleware-net

  product-service-3:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    image: product-service:latest
    hostname: product-3
    expose:
      - "8080"
      - "5005"
    environment:
      - JAVA_TOOL_OPTIONS=--enable-preview -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5007 -Djava.net.preferIPv4Stack=true -Dio.netty.resolver.dns.ndots=1 -Dio.netty.resolver.dns.noSearchDomains=true -Dio.netty.resolver.dns.queryTimeoutMillis=10000
      - SERVER_PORT=8080
      - SERVER_CONTEXT_PATH=/product
      - SECURITY_TYPE=BASIC_AUTH
      - REGISTRY_ENDPOINT=http://registry:8080/registry
      - MONGO_URI=mongodb://mongo:27017/product
      - GRAPHQL_ENABLED=true
      - GRAPHQL_PRODUCT_CLUSTER_NAME=product
      - GRAPHQL_PRODUCT_NAMESPACE=product
      - SPRING_PROFILES_ACTIVE=local
      - REGISTRY_CONSISTENCY_SCHEDULER_ENABLED=true
      - REGISTRY_CONSISTENCY_SCHEDULER_CRON=*/10 * * * * *
      - LOG_API_KEY=${LOG_API_KEY}
      - LOG_REQUEST_ENABLED=true
      - LOG_RESPONSE_ENABLED=true
      - LOG_RESPONSE_TIME_ENABLED=false
      - JMS_PASSWORD=${JMS_PASSWORD}
      - OAUTH2_ISSUER_URI=http://keycloak:8080/realms/spring-middleware
      - OAUTH2_JWK_SET_URI=http://keycloak:8080/realms/spring-middleware/protocol/openid-connect/certs
      - OAUTH2_AUTHORITIES_CLAIM_PATH=$$.resource_access.product-service.roles[*]
      - API_KEY_PRODUCT_ADMIN=${API_KEY_PRODUCT_ADMIN}
      - API_KEY_PRODUCT_WRITER=${API_KEY_PRODUCT_WRITER}
      - API_KEY_PRODUCT_READER=${API_KEY_PRODUCT_READER}
      - OAUTH2_TOKEN_URI_PRODUCT_SERVICE=http://keycloak:8080/realms/spring-middleware/protocol/openid-connect/token
      - BASIC_AUTH_PRODUCT_ADMIN_PASSWORD=${BASIC_AUTH_PRODUCT_ADMIN_PASSWORD}
    depends_on:
      - mongo
      - registry
    networks:
      - middleware-net

  wiremock:
    image: wiremock/wiremock:latest
    container_name: product
    hostname: product
    ports:
      - "8089:8080"
    volumes:
      - ./wiremock:/home/wiremock
    networks:
      middleware-net:
        aliases:
          - product

networks:
  middleware-net:
    driver: bridge
    name: middleware-net

volumes:
  mongo-data:
