version: '3.8'

services:
  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - "27018:27017" # Expose for local access if running app outside docker too
    environment:
      MONGO_INITDB_DATABASE: catalog
    volumes:
      - mongo-data:/data/db
    networks:
      - middleware-net

  catalog-service:
    build:
      context: ./catalog-service
      dockerfile: Dockerfile
    image: catalog-service:latest
    ports:
      - "8070:8080"
      - "5006:5005"
    environment:
      - JAVA_TOOL_OPTIONS= -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - SERVER_PORT=8080
      - REGISTRY_ENDPOINT=http://registry:8080/registry
      - SERVER_CONTEXT_PATH=/catalog
      - MONGO_URI=mongodb://mongo:27017/catalog
      - REDIS_ADDRESS=redis://redis:6379
      - SPRING_PROFILES_ACTIVE=local
      - GRAPHQL_ENABLED=false
    depends_on:
      - mongo
    networks:
      - middleware-net

networks:
  middleware-net:
    external: true

volumes:
  mongo-data:
