schema: product-service/schema.graphql
documents: product-service/**/*.graphql
extensions:
  endpoints:
    product:
      url: http://localhost:8090/product/graphql
      headers:
        user-agent: "JS GraphQL"
      introspect: true
    catalog:
        url: http://localhost:8070/catalog/graphql
        headers:
            user-agent: "JS GraphQL"
            Authorization: "Basic ${BASIC_CATALOG_AUTH_TOKEN}"
        introspect: true
    gateway:
        url: http://localhost:8060/graphql
        headers:
            user-agent: "JS GraphQL"
        introspect: true



