schema: product-service/schema.graphql
documents: product-service/**/*.graphql
extensions:
  endpoints:
    default:
      url: http://localhost:8082/product/graphql
      headers:
        user-agent: "JS GraphQL"
      introspect: true



