server:
  port: ${SERVER_PORT:8083}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/}


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    io.github.spring.middleware: ${LOG_LEVEL_PACKAGE:INFO}
    io.github.spring.middleware.ai.rag.chunk: INFO
    io.github.spring.middleware.scheduler: ERROR
    io.github.spring:.middleware.jms: ERROR
    org.springframework.security: ERROR
    org.springframework.security.web: ERROR
    root: ${LOG_LEVEL_ROOT:ERROR}

catalog:
  document-source:
    rest:
      url: ${CATALOG_DOCUMENT_SOURCE_URL:http://localhost:8070/catalog}
      token-uri: ${CATALOG_DOCUMENT_SOURCE_TOKEN_URI:http://localhost:8081/realms/spring-middleware/protocol/openid-connect/token}
      client-id: ${OAUTH2_CLIENT_ID_CATALOG_SERVICE:catalog-service}
      client-secret: ${OAUTH2_CLIENT_SECRET_CATALOG_SERVICE:KPIRHbxU9Ear4qTaE55wKynwhsGtRhI2}
      scopes: catalog.read catalog.write
    graphql:
      url: ${CATALOG_GRAPHQL_DOCUMENT_SOURCE_URL:http://localhost:8060/graphql}
      items-per-page: 10
      query-path: classpath:/query.graphql


middleware:
  log:
    apiKey: ${LOG_API_KEY}
    request:
      enabled: ${LOG_REQUEST_ENABLED:true}
    response:
      enabled: ${LOG_RESPONSE_ENABLED:true}
    responseTime:
      enabled: ${LOG_RESPONSE_TIME_ENABLED:false}
    exclude:
      urlPatterns:
        - /api-docs/**
        - /swagger-ui.html
        - /swagger-ui/**
        - /_alive
        - /graphql
        - /graphql/_alive
        - /graphql/schema-metadata
        - /api/v1/chat/**

  clients:
    enabled: false

  security:
    type: ${SECURITY_TYPE:NONE} # Options: NONE, BASIC_AUTH, JWT, OUAHT2, API_KEY

  ai:
    document:
      sources:
        documentation:
          enabled: true
          system-context-path: classpath:/context/documentation.context
          type: FILE_SYSTEM
          file-system:
            paths:
              - /app/rag

        catalogs-summary:
          enabled: false
          system-context-path: classpath:/context/catalogs.context
          type: CUSTOM
          chunker: catalogs-chunker
          provider-name: catalogs-rest-provider

        catalogs-full:
          enabled: true
          system-context-path: classpath:/context/catalogs.context
          type: CUSTOM
          chunker: catalogs-chunker
          provider-name: catalogs-graphql-provider

      indexing:
        enabled: true
        index-on-startup: ${INDEX_ON_STARTUP:true}
        sources:
          documentation:
            vector-type: QDRANT
            chunker: documentation-chunker
            vector-namespace: documentation
            embedding-model: nomic-embed-text
            top-k: 5
            document-indexer-type: CHUNKER

          catalogs-summary:
            vector-type: QDRANT
            chunker: catalogs-chunker
            planner-path: classpath:/planner/catalogs.planner
            vector-namespace: catalogs-summary
            embedding-model: mxbai-embed-large
            top-k: 10
            document-indexer-type: CHUNKER

          catalogs-full:
            vector-type: QDRANT
            chunker: catalogs-chunker
            planner-path: classpath:/planner/catalogs-qwen.planner
            vector-namespace: catalogs-full
            embedding-model: mxbai-embed-large
            planner-model: qwen2.5:7b-instruct
            top-k: 10
            document-indexer-type: CHUNKER

    document-chunkers:
      documentation-chunker:
        type: MARKDOWN
        markdown:
          max-chars: 2000
          min-chars: 200
          split-by-headings: true
          max-heading-level: 6
          include-heading-in-chunk: true
          preserve-heading-path: true
          split-by-paragraphs: true
          split-by-sentences: false
          detect-code-blocks: true
          keep-code-blocks-intact: true
          trim: true
          remove-empty-lines: false
          include-line-numbers: false

      catalogs-chunker:
        type: JSON
        json:
          definitions:
            catalogs-summary:
              rules-paths:
                - classpath:rules/catalogs-summary.yml
            catalogs-full:
              rules-paths:
                - classpath:rules/catalogs-full.yml

    vector-store:
      in-memory:
        enabled: false
      mongo:
        enabled: false
      qdrant:
        enabled: true
        url: ${QDRANT_URL:http://localhost:6333}

    provider:
      enabled: true
      ollama:
        models:
          - qwen2.5:7b-instruct
          - mxbai-embed-large
          - nomic-embed-text
        baseUrl: ${OLLAMA_BASE_URL:http://localhost:11434}

      openai:
        enabled: true
        models:
          - gpt-5
          - gpt-4.1-mini
          - text-embedding-3-small

        apiKey: ${OPENAI_API_KEY}
        baseUrl: ${OPENAI_BASE_URL:https://api.openai.com/v1}
        temperature: 0.1
        maxTokens: 3000





