query GetCatalogs($page: Int!, $size: Int!, $sort: String!, $productSort: String!) {
    catalogs(page: $page, size: $size, sort: $sort) {
        content {
            id
            name
            description
            status
            products(sort: $productSort) {
                __typename
                ... on PhysicalProduct {
                    id
                    name
                    sku
                    description
                    productType
                    dimensions {
                        length
                        width
                        height
                    }
                    price {
                        amount
                        currency
                    }
                    reviews {
                        id
                        comment
                        rating
                    }
                }
                ... on DigitalProduct {
                    id
                    name
                    sku
                    description
                    productType
                    downloadUrl
                    fileFormat
                    fileSize
                    price {
                        amount
                        currency
                    }
                    reviews {
                        id
                        comment
                        rating
                    }
                }
            }
        }
        totalElements
        totalPages
    }
}